### ISSUE TITLE
Regarding Datasets

### ISSUE THREAD

**Issue by rishyjee** [sdrabb/argumentation_mining_models#1]
Hey, @sdrabb this is Rishabh here. Actually I was working on IBM's argument mining dataset and their model. I find your lstm model really interesting. According to your readme file, this lstm model is trained on IBM Datasets. 
Could you please share the datasets which you are using for score.py  "data/arg_mining_new/topic_{}_test/topic_name.txt " . To what this link is referring too. I mean I am not getting your data/arg_mining file itself in the entire library. 
Please do let me know as soon as possible. 

Thank you.
Regards,
Rishabh Yadav.

**Comment by sdrabb** [comment]
Hello @rishyjee, you can download dataset from [here](https://www.research.ibm.com/haifa/dept/vst/files/IBM_Debater_(R)_CE-ACL-2014.v0.zip).
